import { toPng, toSvg } from 'html-to-image'
import type { DiagramNode, DiagramEdge } from '../../types/diagram'

/**
 * Exports the current diagram container as a high-resolution PNG image.
 */
export async function exportPng(): Promise<void> {
  try {
    const el = document.getElementById('sys-diagram')
    if (!el) {
      console.error('Export target not found')
      return
    }
    const url = await toPng(el, { 
      backgroundColor: '#ffffff', 
      pixelRatio: 2,
      cacheBust: true,
      skipFonts: true,
    })

    trigger(url, 'diagram.png')
  } catch (err) {
    console.error('PNG Export failed:', err)
  }
}

/**
 * Exports the current diagram container as an SVG file.
 */
export async function exportSvgFile(): Promise<void> {
  try {
    const el = document.getElementById('sys-diagram')
    if (!el) return
    const url = await toSvg(el, { 
      backgroundColor: '#ffffff',
      skipFonts: true,
    })

    trigger(url, 'diagram.svg')
  } catch (err) {
    console.error('SVG Export failed:', err)
  }
}



/**
 * Generates and downloads a Mermaid.js flowchart representation of the diagram.
 * @param nodes - Current collection of diagram nodes
 * @param edges - Current collection of diagram edges
 */
export function exportMermaid(nodes: DiagramNode[], edges: DiagramEdge[]): void {
  const lines = ['flowchart TD']
  nodes.forEach((n) => {
    const id = n.id.replace(/-/g, '_')
    const label = (n.data.label as string).replace(/"/g, "'")
    lines.push(`  ${id}["${label}"]`)
  })
  edges.forEach((e) => {
    lines.push(`  ${e.source.replace(/-/g, '_')} --> ${e.target.replace(/-/g, '_')}`)
  })
  blob(lines.join('\n'), 'diagram.mmd')
}

/**
 * Generates a basic Terraform configuration (HCL) boilerplate based on the diagram nodes.
 * Maps recognized subtypes (e.g., 'lambda', 's3') to AWS resource blocks.
 * @param nodes - Current collection of diagram nodes
 * @param edges - Current collection of diagram edges (used for commentary only)
 */
export function exportTerraform(nodes: DiagramNode[], edges: DiagramEdge[]): void {
  type Gen = (n: DiagramNode) => string
  const map: Record<string, Gen> = {
    'api-gateway': (n) => tfBlock('aws_api_gateway_rest_api', n, `name = "${n.data.label as string}"`),
    'ec2':         (n) => tfBlock('aws_instance', n, `ami = "ami-0c55b159cbfafe1f0"\n  instance_type = "t3.micro"`),
    's3':          (n) => tfBlock('aws_s3_bucket', n, `bucket = "${slug(n)}-bucket"`),
    'lambda':      (n) => tfBlock('aws_lambda_function', n, `function_name = "${slug(n)}"\n  runtime = "nodejs20.x"\n  handler = "index.handler"\n  role = aws_iam_role.lambda_role.arn\n  filename = "${slug(n)}.zip"`),
    'postgres':    (n) => tfBlock('aws_db_instance', n, `engine = "postgres"\n  engine_version = "15"\n  instance_class = "db.t3.micro"\n  username = "admin"\n  password = var.db_password\n  skip_final_snapshot = true`),
    'redis':       (n) => tfBlock('aws_elasticache_cluster', n, `engine = "redis"\n  node_type = "cache.t3.micro"\n  num_cache_nodes = 1\n  parameter_group_name = "default.redis7"`),
  }

  const header = [
    '# Generated by SysDesign Visualizer — review before applying\n',
    'terraform {\n  required_providers {\n    aws = { source = "hashicorp/aws", version = "~> 5.0" }\n  }\n}\n',
    'provider "aws" { region = "us-east-1" }\n',
  ]

  const resources = nodes.map((n) => {
    const gen = map[n.data.subtype as string]
    return gen ? gen(n) : `# ${n.data.label as string} (${n.data.subtype as string}) — manual resource needed`
  })

  const deps = edges.length
    ? ['\n# Connections', ...edges.map((e) => {
        const src = nodes.find((n) => n.id === e.source)?.data.label ?? e.source
        const tgt = nodes.find((n) => n.id === e.target)?.data.label ?? e.target
        return `# ${src as string} --> ${tgt as string}`
      })]
    : []

  blob([...header, ...resources, ...deps].join('\n'), 'main.tf')
}

/**
 * Generates and downloads a Structurizr DSL workspace representation.
 * Maps C4 categories and subtypes to their respective DSL elements (person, softwareSystem, container, component).
 * @param nodes - Collection of diagram nodes
 * @param edges - Collection of diagram edges
 */
export function exportStructurizr(nodes: DiagramNode[], edges: DiagramEdge[]): void {
  const rootNodes = nodes.filter(n => !n.parentId)
  const modelLines: string[] = []

  const renderNode = (n: DiagramNode, depth: number) => {
    const indent = '    '.repeat(depth)
    const subtype = n.data.subtype as string
    const label = (n.data.label as string).replace(/"/g, "'")
    const desc = (n.data.description as string || '').replace(/"/g, "'")
    const id = n.id.replace(/-/g, '_')
    const children = nodes.filter(child => child.parentId === n.id)

    let keyword = 'container'
    if (subtype === 'c4-person') keyword = 'person'
    else if (subtype === 'c4-system' || subtype === 'c4-external-system' || (n.type === 'group' && depth === 2)) keyword = 'softwareSystem'
    else if (subtype.includes('component') || ['c4-controller', 'c4-service', 'c4-repository', 'c4-gateway'].includes(subtype)) keyword = 'component'
    else if (n.type === 'group') keyword = 'container'

    const tech = ((n.data.technology as string) || "").replace(/"/g, "'")
    const techArg = tech ? ` "${tech}"` : ""

    if (children.length > 0) {
      modelLines.push(`${indent}${id} = ${keyword} "${label}" "${desc}"${techArg} {`)
      children.forEach(child => renderNode(child, depth + 1))
      modelLines.push(`${indent}}`)
    } else {
      modelLines.push(`${indent}${id} = ${keyword} "${label}" "${desc}"${techArg}`)
    }
  }

  rootNodes.forEach(rn => renderNode(rn, 2))

  const relationshipLines = edges.map((e) => {
    const src = e.source.replace(/-/g, '_')
    const tgt = e.target.replace(/-/g, '_')
    const label = (typeof e.label === 'string' ? e.label : (e.data?.label as string) || 'Uses').replace(/"/g, "'")
    return `        ${src} -> ${tgt} "${label}"`
  })

  const dsl = [
    'workspace {',
    '    model {',
    ...modelLines,
    '',
    ...relationshipLines,
    '    }',
    '    views {',
    '        systemContext nodes {',
    '            include *',
    '            autolayout lr',
    '        }',
    '        container nodes {',
    '            include *',
    '            autolayout lr',
    '        }',
    '        component nodes {',
    '            include *',
    '            autolayout lr',
    '        }',
    '        theme default',
    '    }',
    '}'
  ].join('\n')

  blob(dsl, 'workspace.dsl')
}

function slug(n: DiagramNode) {
  return (n.data.label as string).toLowerCase().replace(/[^a-z0-9]/g, '_')
}

function tfBlock(resource: string, n: DiagramNode, body: string) {
  return `resource "${resource}" "${slug(n)}" {\n  ${body}\n  tags = { Name = "${n.data.label as string}" }\n}\n`
}

function trigger(url: string, filename: string) {
  const a = document.createElement('a')
  a.style.display = 'none'
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
}


function blob(content: string, filename: string) {
  const url = URL.createObjectURL(new Blob([content], { type: 'text/plain' }))
  trigger(url, filename)
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}
