/**
 * @fileoverview AI Chat Drawer component.
 * Slides over from the right side of the screen providing a full conversational
 * interface to generate and modify system architecture and C4 diagrams.
 */

import * as React from "react";
import {
  IconAlertCircle,
  IconBulb,
  IconCheck,
  IconChevronRight,
  IconKey,
  IconLayout,
  IconListDetails,
  IconLoader2,
  IconMessageQuestion,
  IconRefresh,
  IconSend,
  IconServer,
  IconSettings,
  IconShieldLock,
  IconSitemap,
  IconSparkles,
  IconTrash,
  IconX,
} from "@tabler/icons-react";
import { Button } from "@/components/ui/button";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { cn } from "@/lib/utils";
import {
  
  PROVIDER_META,
  useAIChatMessages,
  useAIDrawer,
  useAIKeys,
  useAIPrompt
} from "@/store/ai.store";
import type {AIProvider} from "@/store/ai.store";
import { callAI } from "@/lib/ai.service";
import { ARCHITECTURE_SYSTEM_PROMPT, C4_SYSTEM_PROMPT } from "@/lib/ai.prompts";
import { setDiagramFromAI, useCanvasStore } from "@/store/canvas.store";
import type { DiagramEdge, DiagramNode, NodeMeta } from "@/types/diagram";
import { MarkerType } from "@xyflow/react";
import AISettings from "@/components/ai/AISettings";
import { Loader } from "../ui/loader";
import {  Textarea } from "@/components/ui/textarea";
import type {AutosizeTextAreaRef} from "@/components/ui/textarea";

/** Raw node structure returned by the AI provider JSON response */
interface AINode {
  id: string;
  subtype: string;
  label: string;
  description: string;
  x: number;
  y: number;
}

/** Raw edge connection returned by the AI provider JSON response */
interface AIEdge {
  source: string;
  target: string;
  label: string;
}

/** Complete graph payload generated by the AI model */
interface AIGraphResult {
  nodes: Array<AINode>;
  edges: Array<AIEdge>;
  explanation?: string;
}

const SUBTYPE_ICON: Record<string, string> = {
  "api-gateway": "IconApi",
  service: "IconBox",
  "message-queue": "IconStack2",
  "load-balancer": "IconArrowsSplit2",
  ec2: "IconServer",
  s3: "IconBucket",
  cdn: "IconWorld",
  lambda: "IconBolt",
  postgres: "IconDatabase",
  redis: "IconCpu",
  mongo: "IconLeaf",
  elasticsearch: "IconZoomCode",
  "web-app": "IconBrowser",
  mobile: "IconDeviceMobile",
  component: "IconLayoutGrid",
  bff: "IconPlugConnected",
  "c4-person": "IconUser",
  "c4-system": "IconBox",
  "c4-container": "IconStack2",
  "c4-component": "IconPuzzle",
};

const SUBTYPE_CATEGORY: Record<string, string> = {
  "api-gateway": "microservice",
  service: "microservice",
  "message-queue": "microservice",
  "load-balancer": "microservice",
  ec2: "cloud",
  s3: "cloud",
  cdn: "cloud",
  lambda: "cloud",
  postgres: "database",
  redis: "database",
  mongo: "database",
  elasticsearch: "database",
  "web-app": "frontend",
  mobile: "frontend",
  component: "frontend",
  bff: "frontend",
  "c4-person": "c4",
  "c4-system": "c4",
  "c4-container": "c4",
  "c4-component": "c4",
};

function parseAIResponse(raw: string): AIGraphResult {
  const cleaned = raw
    .replace(/```json\s*/gi, "")
    .replace(/```\s*/g, "")
    .trim();
  const parsed = JSON.parse(cleaned);
  if (!Array.isArray(parsed.nodes) || !Array.isArray(parsed.edges)) {
    throw new Error("AI response missing nodes or edges array");
  }
  return parsed as AIGraphResult;
}

function toCanvasNodes(
  aiNodes: Array<AINode>,
  mode: "architecture" | "c4",
): Array<DiagramNode> {
  return aiNodes.map((n) => {
    const subtype = n.subtype.toLowerCase();
    const category = (SUBTYPE_CATEGORY[subtype] ??
      (mode === "c4" ? "c4" : "microservice")) as NodeMeta["category"];
    const icon = SUBTYPE_ICON[subtype] ?? "IconBox";
    return {
      id: n.id,
      type: "diagramNode",
      position: { x: n.x, y: n.y },
      data: {
        subtype,
        label: n.label,
        description: n.description,
        category,
        icon,
      } as NodeMeta,
    };
  });
}

function toCanvasEdges(
  aiEdges: Array<AIEdge>,
  mode: "architecture" | "c4",
): Array<DiagramEdge> {
  return aiEdges.map((e, i) => ({
    id: `ai-e-${i + 1}`,
    source: e.source,
    target: e.target,
    type: "smoothstep",
    label: e.label || undefined,
    data: mode === "c4" ? { label: e.label } : {},
    style: { stroke: "var(--border)", strokeWidth: 1.5 },
    markerEnd: { type: MarkerType.ArrowClosed, color: "var(--border)" },
  }));
}

const ARCH_SUGGESTIONS = [
  {
    icon: IconSitemap,
    label: "E-commerce Microservices",
    prompt:
      "Design an e-commerce system with product catalog, cart, checkout, payment gateway, inventory, and order service with PostgreSQL and Redis cache.",
  },
  {
    icon: IconListDetails,
    label: "Real-time Chat Architecture",
    prompt:
      "Design a scalable real-time chat application with WebSocket gateway, message queue, presence service, MongoDB, and Redis pub/sub.",
  },
  {
    icon: IconBulb,
    label: "API-First SaaS Platform",
    prompt:
      "Design a multi-tenant SaaS backend with API gateway, auth service, billing microservice, webhooks worker, and PostgreSQL database.",
  },
  {
    icon: IconMessageQuestion,
    label: "Streaming Data Pipeline",
    prompt:
      "Design a high-throughput data ingestion pipeline with Kafka, stream processing workers, Elasticsearch search index, and S3 lake.",
  },
];

const C4_SUGGESTIONS = [
  {
    icon: IconSitemap,
    label: "Online Banking System",
    prompt:
      "Create a C4 model for an online banking platform with customer web portal, mobile app, API gateway, core banking system, and database.",
  },
  {
    icon: IconListDetails,
    label: "Healthcare EHR Platform",
    prompt:
      "Create a C4 model for an electronic healthcare records system with patient portal, doctor dashboard, appointment scheduler, and HIPAA-compliant DB.",
  },
  {
    icon: IconBulb,
    label: "IoT Telemetry Platform",
    prompt:
      "Create a C4 model for an IoT device management system with MQTT broker, device registry, time-series data storage, and analytics API.",
  },
  {
    icon: IconMessageQuestion,
    label: "Delivery & Logistics Hub",
    prompt:
      "Create a C4 model for a food delivery platform connecting customers, restaurant apps, rider tracking service, and payment processor.",
  },
];

type Status = "idle" | "loading" | "success" | "error";

export default function AIChatDrawer() {
  const { isOpen, close } = useAIDrawer();
  const { keys, hasAny } = useAIKeys();
  const { prompt: sharedPrompt, setPrompt: setSharedPrompt } = useAIPrompt();
  const { messages, addMessage, clearMessages } = useAIChatMessages();
  const diagramMode = useCanvasStore((s) => s.diagramMode);

  const [prompt, setPrompt] = React.useState("");
  const [selectedProvider, setSelectedProvider] =
    React.useState<AIProvider | null>(null);
  const [status, setStatus] = React.useState<Status>("idle");
  const [errorMsg, setErrorMsg] = React.useState("");
  const [lastPrompt, setLastPrompt] = React.useState("");
  const [showSettingsModal, setShowSettingsModal] = React.useState(false);

  const messagesEndRef = React.useRef<HTMLDivElement>(null);
  const textareaRef = React.useRef<AutosizeTextAreaRef>(null);

  const isC4 = diagramMode === "c4";
  const suggestions = isC4 ? C4_SUGGESTIONS : ARCH_SUGGESTIONS;

  // Auto-select first available provider
  React.useEffect(() => {
    if (keys.length > 0) {
      if (
        !selectedProvider ||
        !keys.some((k) => k.provider === selectedProvider)
      ) {
        setSelectedProvider(keys[0].provider);
      }
    } else {
      setSelectedProvider(null);
    }
  }, [keys, selectedProvider]);

  // Handle incoming shared prompt
  React.useEffect(() => {
    if (sharedPrompt) {
      setPrompt(sharedPrompt);
      setSharedPrompt("");
      if (isOpen) {
        textareaRef.current?.focus();
      }
    }
  }, [sharedPrompt, isOpen]);

  // Auto-scroll to bottom of chat
  React.useEffect(() => {
    if (isOpen) {
      messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
    }
  }, [messages, status, isOpen]);

  // Focus textarea when drawer opens
  React.useEffect(() => {
    if (isOpen) {
      setTimeout(() => {
        textareaRef.current?.focus();
      }, 150);
    }
  }, [isOpen]);

  // Close on Escape key
  React.useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape" && isOpen && !showSettingsModal) {
        close();
      }
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [isOpen, showSettingsModal, close]);

  const canSend =
    prompt.trim().length > 0 && !!selectedProvider && status !== "loading";

  const handleSend = async (overridePrompt?: string) => {
    const text = (overridePrompt ?? prompt).trim();
    if (!text || !selectedProvider) return;

    // Add user message
    addMessage({
      role: "user",
      content: text,
    });

    setStatus("loading");
    setErrorMsg("");
    setLastPrompt(text);
    setPrompt("");

    try {
      const systemPrompt = isC4 ? C4_SYSTEM_PROMPT : ARCHITECTURE_SYSTEM_PROMPT;
      const response = await callAI(selectedProvider, [
        { role: "system", content: systemPrompt },
        ...messages.slice(-6).map((m) => ({
          role: m.role as "user" | "assistant",
          content: m.content,
        })),
        { role: "user", content: text },
      ]);

      const result = parseAIResponse(response.content);
      const canvasNodes = toCanvasNodes(result.nodes, diagramMode);
      const canvasEdges = toCanvasEdges(result.edges, diagramMode);

      setDiagramFromAI(canvasNodes, canvasEdges);
      setStatus("success");

      // Add assistant message
      addMessage({
        role: "assistant",
        content: `Generated ${isC4 ? "C4 Model" : "Architecture"} diagram with **${canvasNodes.length} nodes** and **${canvasEdges.length} connections**.`,
        diagramGenerated: {
          nodeCount: canvasNodes.length,
          edgeCount: canvasEdges.length,
          title: text.length > 35 ? text.substring(0, 35) + "…" : text,
        },
      });
    } catch (err: any) {
      console.error(err);
      const msg = err?.message ?? "Failed to generate diagram";
      setErrorMsg(msg);
      setStatus("error");

      addMessage({
        role: "assistant",
        content: `Error generating diagram: ${msg}. Please check your API key and prompt.`,
      });
    }
  };

  const handleRetry = () => {
    if (lastPrompt) {
      handleSend(lastPrompt);
    }
  };

  if (!isOpen) return null;

  return (
    <>
      {/* Backdrop overlay for mobile screens */}
      <div
        className="fixed inset-0 z-40 bg-background/50 backdrop-blur-xs sm:hidden animate-in fade-in duration-150"
        onClick={close}
      />

      {/* AI Chat Drawer Container */}
      <aside
        aria-label="AI Assistant Drawer"
        className={cn(
          "fixed right-0 top-0 bottom-0 z-50 flex flex-col w-full sm:w-96 md:w-105",
          "bg-card/95 backdrop-blur-xs border-l border-border shadow-xl",
          "animate-in slide-in-from-right duration-200",
        )}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-3.5 h-11 border-b border-border bg-muted/20 shrink-0">
          <div className="flex items-center gap-2">
            <div className="size-5 rounded-xs bg-primary/10 flex items-center justify-center text-primary">
              <IconSparkles size={12} />
            </div>
            <div className="flex items-center gap-1.5">
              <h6 className="text-xs font-semibold text-foreground">
                AI Architecture
              </h6>
              <span className="text-[9.5px] font-mono font-medium px-1.5 py-0.5 rounded-xs bg-primary/10 text-primary border border-primary/20">
                {isC4 ? "C4" : "System"}
              </span>
            </div>
          </div>

          <div className="flex items-center gap-1">
            <Tooltip>
              <TooltipTrigger
                render={
                  <Button
                    variant="ghost"
                    size="icon"
                    icon={<IconSettings size={14} />}
                    iconPlacement="left"
                    onClick={() => setShowSettingsModal(true)}
                    className="p-1 rounded text-muted-foreground hover:text-foreground"
                    title="AI Provider Settings"
                  />
                }
              />
              <TooltipContent side="bottom">API Keys</TooltipContent>
            </Tooltip>

            {messages.length > 0 && (
              <Tooltip>
                <TooltipTrigger
                  render={
                    <Button
                      variant="ghost"
                      size="icon"
                      icon={<IconTrash size={14} />}
                      iconPlacement="left"
                      onClick={clearMessages}
                      className="p-1 rounded text-muted-foreground hover:text-destructive hover:bg-destructive/10"
                      title="Clear Chat History"
                    />
                  }
                />
                <TooltipContent side="bottom">Clear Chat</TooltipContent>
              </Tooltip>
            )}

            <Button
              variant="ghost"
              size="icon"
              icon={<IconX size={15} />}
              iconPlacement="left"
              onClick={close}
              className="p-1 rounded text-muted-foreground hover:text-foreground ml-1"
            />
          </div>
        </div>

        {/* Provider Selector Bar */}
        {hasAny && (
          <div className="flex items-center justify-between px-3 py-1.5 bg-muted/30 border-b border-border/50 shrink-0">
            <span className="text-[10px] font-mono text-muted-foreground flex items-center gap-1">
              <IconServer size={11} />
              Provider:
            </span>
            <div className="flex items-center gap-1">
              {keys.map((k) => {
                const meta = PROVIDER_META[k.provider];
                const isActive = selectedProvider === k.provider;
                return (
                  <Button
                    key={k.provider}
                    variant={isActive ? "secondary" : "ghost"}
                    size="xs"
                    icon={
                      <span
                        className="size-1.5 rounded-full shrink-0"
                        style={{ background: meta.color }}
                      />
                    }
                    iconPlacement="left"
                    onClick={() => setSelectedProvider(k.provider)}
                    className={cn(
                      "flex items-center gap-1 px-2 py-0.5 h-6 rounded text-[11px] font-medium transition-colors",
                      isActive
                        ? "bg-card text-foreground shadow-xs border border-border"
                        : "text-muted-foreground hover:text-foreground hover:bg-muted/60",
                    )}
                  >
                    {meta.label.split(" ")[0]}
                  </Button>
                );
              })}
            </div>
          </div>
        )}

        {/* Scrollable Conversation Feed */}
        <div className="flex-1 overflow-y-auto p-3.5 space-y-3 custom-scrollbar">
          {/* Missing Keys Banner */}
          {!hasAny && (
            <div className="p-3 rounded-md border border-primary/20 bg-primary/5 text-foreground space-y-2">
              <div className="flex items-start gap-2">
                <IconKey size={15} className="text-primary shrink-0 mt-0.5" />
                <div className="space-y-1.5">
                  <h6 className="text-xs font-semibold text-foreground">
                    Connect AI Provider
                  </h6>
                  <p className="text-[11px] text-muted-foreground leading-relaxed">
                    Add your OpenAI, Anthropic, or Gemini API key to enable
                    AI-powered architecture generation.
                  </p>
                  <Button
                    onClick={() => setShowSettingsModal(true)}
                    size="xs"
                    className="mt-1"
                  >
                    Configure API Keys
                  </Button>
                </div>
              </div>
            </div>
          )}

          {/* Empty State / Suggestions */}
          {messages.length === 0 && (
            <div className="space-y-2 py-1">
              <div className="flex items-center justify-between text-[11px] font-medium text-foreground px-0.5">
                <span>Suggested Prompts</span>
                <span className="font-mono text-[9px] text-muted-foreground">
                  click to insert
                </span>
              </div>
              <div className="grid grid-cols-1 gap-1.5">
                {suggestions.map((s) => (
                  <Button
                    key={s.label}
                    variant="ghost"
                    size="sm"
                    onClick={() => {
                      if (hasAny) {
                        handleSend(s.prompt);
                      } else {
                        setPrompt(s.prompt);
                        textareaRef.current?.focus();
                      }
                    }}
                    className="w-full h-auto flex items-start gap-2.5 p-2.5 rounded-md border border-border bg-card hover:bg-muted/60 text-left transition-colors group shadow-xs font-normal"
                  >
                    <div className="p-1 rounded bg-muted text-muted-foreground group-hover:text-primary transition-colors shrink-0 mt-0.5">
                      <s.icon size={13} stroke={1.5} />
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="text-xs font-medium text-foreground group-hover:text-primary transition-colors">
                        {s.label}
                      </div>
                      <div className="text-[10px] text-muted-foreground line-clamp-2 mt-0.5 leading-snug">
                        {s.prompt}
                      </div>
                    </div>
                    <IconChevronRight
                      size={12}
                      className="text-muted-foreground/40 group-hover:text-primary group-hover:translate-x-0.5 transition-all shrink-0 mt-1"
                    />
                  </Button>
                ))}
              </div>
            </div>
          )}

          {/* Chat Messages */}
          {messages.map((msg) => (
            <div
              key={msg.id}
              className={cn(
                "flex flex-col gap-1",
                msg.role === "user" ? "items-end" : "items-start",
              )}
            >
              <div className="flex items-center gap-1 px-0.5 text-[9px] font-mono text-muted-foreground">
                <span>{msg.role === "user" ? "You" : "SysDesign AI"}</span>
                <span>·</span>
                <span>
                  {new Date(msg.timestamp).toLocaleTimeString([], {
                    hour: "2-digit",
                    minute: "2-digit",
                  })}
                </span>
              </div>

              <div
                className={cn(
                  "px-3 py-2 rounded-md text-xs leading-relaxed max-w-[92%]",
                  msg.role === "user"
                    ? "bg-primary text-primary-foreground"
                    : "bg-muted/40 border border-border/80 text-foreground space-y-2",
                )}
              >
                <div className="whitespace-pre-wrap">{msg.content}</div>

                {/* Render Diagram Metadata Badge if generated */}
                {msg.diagramGenerated && (
                  <div className="p-2 rounded bg-card border border-border flex items-center justify-between gap-2 shadow-xs">
                    <div className="flex items-center gap-2 min-w-0">
                      <div className="p-1 bg-primary/10 rounded text-primary shrink-0">
                        <IconLayout size={13} />
                      </div>
                      <div className="min-w-0">
                        <div className="font-medium text-foreground text-[11px] truncate">
                          {msg.diagramGenerated.title || "Architecture Layout"}
                        </div>
                        <div className="text-[9px] font-mono text-muted-foreground">
                          {msg.diagramGenerated.nodeCount} nodes ·{" "}
                          {msg.diagramGenerated.edgeCount} edges
                        </div>
                      </div>
                    </div>
                    <span className="flex items-center gap-0.5 text-[9px] font-mono text-emerald-600 dark:text-emerald-400 bg-emerald-500/10 px-1.5 py-0.5 rounded border border-emerald-500/20">
                      <IconCheck size={10} />
                      Applied
                    </span>
                  </div>
                )}
              </div>
            </div>
          ))}

          {/* Loading Indicator */}
          {status === "loading" && (
            <div className="flex flex-col gap-1 items-start">
              <div className="flex items-center gap-1 px-0.5 text-[9px] font-mono text-muted-foreground">
                <span>SysDesign AI</span>
                <span>·</span>
                <span>Generating</span>
              </div>
              <div className="flex items-center gap-2.5 px-3 py-2 rounded-md bg-muted/40 border border-border">
                <IconLoader2
                  size={14}
                  className="animate-spin text-primary shrink-0"
                />
                <div className="text-xs text-foreground font-medium">
                  Architecting system layout…
                </div>
              </div>
            </div>
          )}

          {/* Generation Error Callout */}
          {status === "error" && (
            <div className="p-2.5 rounded-md bg-destructive/10 border border-destructive/20 flex items-start justify-between gap-2 text-xs">
              <div className="flex items-start gap-2 min-w-0">
                <IconAlertCircle
                  size={14}
                  className="text-destructive shrink-0 mt-0.5"
                />
                <div className="min-w-0">
                  <div className="font-semibold text-destructive text-xs">
                    Generation Error
                  </div>
                  <div className="text-muted-foreground text-[10px] mt-0.5 line-clamp-2">
                    {errorMsg}
                  </div>
                </div>
              </div>
              <Button
                onClick={handleRetry}
                variant="outline"
                size="xs"
                className="shrink-0"
                icon={<IconRefresh size={11} />}
              >
                Retry
              </Button>
            </div>
          )}

          <div ref={messagesEndRef} />
        </div>

        {/* Input Footer */}
        <div className="p-3 border-t border-border/80 bg-muted/10 space-y-1.5 shrink-0">
          <div className="relative rounded-md border border-border bg-card shadow-xs focus-within:border-primary focus-within:ring-1 focus-within:ring-primary/30 transition-colors overflow-hidden">
            <Textarea
              ref={textareaRef}
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter" && !e.shiftKey) {
                  e.preventDefault();
                  if (canSend) handleSend();
                }
              }}
              disabled={status === "loading" || !hasAny}
              placeholder={
                !hasAny
                  ? "Configure an API key above to start prompting…"
                  : isC4
                    ? "Describe C4 model (e.g. Banking system with API and core DB)…"
                    : "Describe architecture (e.g. Microservices backend with Kafka & Postgres)…"
              }
              className="w-full resize-none border-0 shadow-none bg-transparent px-3 pt-2.5 pb-1 text-xs placeholder:text-muted-foreground outline-none leading-relaxed font-sans disabled:opacity-50 focus-visible:ring-0"
            />

            <div className="flex items-center justify-between px-2.5 pb-2 pt-0.5">
              <span className="text-[9px] text-muted-foreground flex items-center gap-1 font-mono">
                <kbd className="px-1 py-0.5 bg-muted rounded border border-border text-[8px]">
                  Enter
                </kbd>
                <span>send</span>
              </span>

              <Button
                onClick={() => handleSend()}
                disabled={!canSend}
                size="xs"
                className="h-6 px-2 text-xs font-medium gap-1"
                icon={
                  status === "loading" ? (
                    <Loader className="animate-spin" />
                  ) : (
                    <IconSend size={11} />
                  )
                }
              >
                <span>Generate</span>
              </Button>
            </div>
          </div>

          <div className="flex items-center justify-between text-[9px] font-mono text-muted-foreground px-0.5">
            <span className="flex items-center gap-1">
              <IconShieldLock size={10} className="text-primary/80" />
              <span>Keys stored locally</span>
            </span>
            {selectedProvider && (
              <span className="uppercase">
                {PROVIDER_META[selectedProvider].label}
              </span>
            )}
          </div>
        </div>
      </aside>

      {/* Embedded Settings Modal */}
      {showSettingsModal && (
        <div className="fixed inset-0 z-[2000] flex items-center justify-center p-4">
          <div
            className="absolute inset-0 bg-background/60 backdrop-blur-xs animate-in fade-in duration-150"
            onClick={() => setShowSettingsModal(false)}
          />
          <div className="relative w-full max-w-md bg-card border border-border rounded-md shadow-xl animate-in zoom-in-98 duration-150 p-4.5 flex flex-col gap-3">
            <div className="flex items-center justify-between border-b border-border/60 pb-2">
              <div className="flex items-center gap-1.5">
                <div className="size-5 rounded-xs bg-primary/10 flex items-center justify-center text-primary">
                  <IconKey size={13} />
                </div>
                <h6 className="text-xs font-semibold text-foreground">
                  AI Provider Keys
                </h6>
              </div>
              <Button
                variant="ghost"
                size="icon"
                icon={<IconX size={14} />}
                iconPlacement="left"
                onClick={() => setShowSettingsModal(false)}
                className="p-1 rounded text-muted-foreground hover:text-foreground"
              />
            </div>
            <AISettings />
          </div>
        </div>
      )}
    </>
  );
}
