/**
 * @fileoverview AI Diagram Generation Assistant drawer panel component.
 * Allows users to describe architecture or C4 diagrams via natural language and stream/insert them onto the canvas.
 */

import * as React from "react";
import {
  IconAlertCircle,
  IconBulb,
  IconCheck,
  IconChevronRight,
  IconListDetails,
  IconLoader2,
  IconMessageQuestion,
  IconRefresh,
  IconSend,
  IconSitemap,
  IconSparkles,
  IconX,
} from "@tabler/icons-react";
import { cn } from "@/lib/utils";
import {
  
  PROVIDER_META,
  useAIKeys,
  useAIPrompt
} from "@/store/ai.store";
import type {AIProvider} from "@/store/ai.store";
import { callAI } from "@/lib/ai.service";
import {
  ARCHITECTURE_SYSTEM_PROMPT,
  C4_SYSTEM_PROMPT,
} from "@/lib/ai.prompts";
import { setDiagramFromAI, useCanvasStore } from "@/store/canvas.store";
import type { DiagramEdge, DiagramNode, NodeMeta } from "@/types/diagram";
import { MarkerType } from "@xyflow/react";
import { Button } from "@/components/ui/button";

/** Raw node structure returned by the AI provider JSON response */
interface AINode {
  id: string;
  subtype: string;
  label: string;
  description: string;
  x: number;
  y: number;
}

/** Raw edge connection returned by the AI provider JSON response */
interface AIEdge {
  source: string;
  target: string;
  label: string;
}

/** Complete graph payload generated by the AI model */
interface AIGraphResult {
  nodes: Array<AINode>;
  edges: Array<AIEdge>;
}

const SUBTYPE_ICON: Record<string, string> = {
  "api-gateway": "IconApi",
  service: "IconBox",
  "message-queue": "IconStack2",
  "load-balancer": "IconArrowsSplit2",
  ec2: "IconServer",
  s3: "IconBucket",
  cdn: "IconWorld",
  lambda: "IconBolt",
  postgres: "IconDatabase",
  redis: "IconCpu",
  mongo: "IconLeaf",
  elasticsearch: "IconZoomCode",
  "web-app": "IconBrowser",
  mobile: "IconDeviceMobile",
  component: "IconLayoutGrid",
  bff: "IconPlugConnected",
  "c4-person": "IconUser",
  "c4-system": "IconBox",
  "c4-container": "IconStack2",
  "c4-component": "IconPuzzle",
};

const SUBTYPE_CATEGORY: Record<string, string> = {
  "api-gateway": "microservice",
  service: "microservice",
  "message-queue": "microservice",
  "load-balancer": "microservice",
  ec2: "cloud",
  s3: "cloud",
  cdn: "cloud",
  lambda: "cloud",
  postgres: "database",
  redis: "database",
  mongo: "database",
  elasticsearch: "database",
  "web-app": "frontend",
  mobile: "frontend",
  component: "frontend",
  bff: "frontend",
  "c4-person": "c4",
  "c4-system": "c4",
  "c4-container": "c4",
  "c4-component": "c4",
};

/**
 * Parses and validates raw model text response into typed graph nodes and edges.
 *
 * @param raw - Raw string received from AI provider
 * @returns Parsed graph structure
 */
function parseAIResponse(raw: string): AIGraphResult {
  const cleaned = raw
    .replace(/```json\s*/gi, "")
    .replace(/```\s*/g, "")
    .trim();
  const parsed = JSON.parse(cleaned);
  if (!Array.isArray(parsed.nodes) || !Array.isArray(parsed.edges)) {
    throw new Error("AI response missing nodes or edges array");
  }
  return parsed as AIGraphResult;
}

/**
 * Converts raw AI generated nodes into ReactFlow diagram node entities.
 *
 * @param aiNodes - Array of raw AI nodes
 * @param mode - Active diagram mode
 * @returns Array of typed diagram nodes
 */
function toCanvasNodes(
  aiNodes: Array<AINode>,
  mode: "architecture" | "c4",
): Array<DiagramNode> {
  return aiNodes.map((n) => {
    const subtype = n.subtype.toLowerCase();
    const category = (SUBTYPE_CATEGORY[subtype] ??
      (mode === "c4" ? "c4" : "microservice")) as NodeMeta["category"];
    const icon = SUBTYPE_ICON[subtype] ?? "IconBox";
    return {
      id: n.id,
      type: "diagramNode",
      position: { x: n.x, y: n.y },
      data: {
        subtype,
        label: n.label,
        description: n.description,
        category,
        icon,
      } as NodeMeta,
    };
  });
}

/**
 * Converts raw AI generated edge connections into ReactFlow diagram edges.
 *
 * @param aiEdges - Array of raw AI edge links
 * @param mode - Active diagram mode
 * @returns Array of typed diagram edges
 */
function toCanvasEdges(
  aiEdges: Array<AIEdge>,
  mode: "architecture" | "c4",
): Array<DiagramEdge> {
  return aiEdges.map((e, i) => ({
    id: `ai-e-${i + 1}`,
    source: e.source,
    target: e.target,
    type: "smoothstep",
    label: e.label || undefined,
    data: mode === "c4" ? { label: e.label } : {},
    style: { stroke: "var(--border)", strokeWidth: 1.5 },
    markerEnd: { type: MarkerType.ArrowClosed, color: "var(--border)" },
  }));
}

const ARCH_SUGGESTIONS = [
  {
    icon: IconSitemap,
    label: "E-commerce microservices",
    prompt:
      "Design an e-commerce system with product catalog, cart, checkout, payment, and order services",
  },
  {
    icon: IconListDetails,
    label: "Real-time chat app",
    prompt:
      "Design a real-time chat application with WebSocket, message queue, and presence service",
  },
  {
    icon: IconBulb,
    label: "API-first SaaS backend",
    prompt:
      "Design an API-first SaaS backend with authentication, billing, multi-tenancy, and webhooks",
  },
  {
    icon: IconMessageQuestion,
    label: "Data pipeline",
    prompt:
      "Design a data ingestion pipeline with Kafka, stream processing, and analytics storage",
  },
];

const C4_SUGGESTIONS = [
  {
    icon: IconSitemap,
    label: "Online banking system",
    prompt:
      "Create a C4 model for an online banking system with customers, mobile app, web portal, and backend services",
  },
  {
    icon: IconListDetails,
    label: "SaaS platform",
    prompt:
      "Create a C4 model for a SaaS project management platform with web app, API, database, and email service",
  },
  {
    icon: IconBulb,
    label: "Healthcare system",
    prompt:
      "Create a C4 model for a healthcare system with patients, doctors, appointment service, and EHR",
  },
  {
    icon: IconMessageQuestion,
    label: "IoT platform",
    prompt:
      "Create a C4 model for an IoT platform with devices, MQTT broker, device registry, and dashboard",
  },
];

type Status = "idle" | "loading" | "success" | "error";

/** Props for the AIPanel component */
interface AIPanelProps {
  /** Callback fired when the user closes the AI drawer panel */
  onClose: () => void;
}

/**
 * AI Assistant drawer interface for prompt submission, provider selection, and direct canvas generation.
 *
 * @param props - AIPanelProps
 * @returns AI Assistant panel component
 */
export default function AIPanel({ onClose }: AIPanelProps) {
  const { keys } = useAIKeys();
  const { prompt: sharedPrompt, setPrompt: setSharedPrompt } = useAIPrompt();
  const diagramMode = useCanvasStore((s) => s.diagramMode);
  const [prompt, setPrompt] = React.useState("");
  const [selectedProvider, setSelectedProvider] =
    React.useState<AIProvider | null>(null);
  const [status, setStatus] = React.useState<Status>("idle");
  const [errorMsg, setErrorMsg] = React.useState("");
  const [lastPrompt, setLastPrompt] = React.useState("");
  const textareaRef = React.useRef<HTMLTextAreaElement>(null);

  const isC4 = diagramMode === "c4";
  const suggestions = isC4 ? C4_SUGGESTIONS : ARCH_SUGGESTIONS;

  React.useEffect(() => {
    if (keys.length > 0 && !selectedProvider) {
      setSelectedProvider(keys[0].provider);
    }
  }, [keys, selectedProvider]);

  React.useEffect(() => {
    if (sharedPrompt) {
      setPrompt(sharedPrompt);
      setSharedPrompt("");
      textareaRef.current?.focus();
    }
  }, [sharedPrompt]);

  const canSend =
    prompt.trim().length > 0 && !!selectedProvider && status !== "loading";

  const handleSend = async (overridePrompt?: string) => {
    const text = (overridePrompt ?? prompt).trim();
    if (!text || !selectedProvider) return;

    setStatus("loading");
    setErrorMsg("");
    setLastPrompt(text);
    setPrompt("");

    try {
      const systemPrompt = isC4 ? C4_SYSTEM_PROMPT : ARCHITECTURE_SYSTEM_PROMPT;
      const response = await callAI(selectedProvider, [
        { role: "system", content: systemPrompt },
        { role: "user", content: text },
      ]);

      const result = parseAIResponse(response.content);
      const nodes = toCanvasNodes(result.nodes, diagramMode);
      const edges = toCanvasEdges(result.edges, diagramMode);

      setDiagramFromAI(nodes, edges);
      setStatus("success");
    } catch (err: any) {
      console.log(err);
      setErrorMsg(err?.message ?? "Unknown error");
      setStatus("error");
    }
  };

  const handleRetry = () => {
    setPrompt(lastPrompt);
    setStatus("idle");
  };

  return (
    <div
      className="flex flex-col bg-card border border-border rounded-lg shadow-xl w-[360px] overflow-hidden animate-in slide-in-from-left-2 fade-in duration-200"
      style={{
        maxHeight: "calc(100vh - 96px)",
      }}
    >
      {/* Header */}
      <div className="flex items-center justify-between px-3.5 py-2.5 border-b border-border/60 shrink-0">
        <div className="flex items-center gap-2">
          <div className="size-5 rounded bg-primary/10 flex items-center justify-center text-primary">
            <IconSparkles size={13} stroke={1.6} />
          </div>
          <div>
            <h6 className="text-xs font-semibold text-foreground">
              AI Assistant
            </h6>
            <p className="text-[10px] font-mono text-muted-foreground leading-none">
              {isC4 ? "C4 Model" : "Architecture"}
            </p>
          </div>
        </div>
        <button
          onClick={onClose}
          className="p-1 rounded text-muted-foreground hover:text-foreground hover:bg-muted transition-colors cursor-pointer"
        >
          <IconX size={14} />
        </button>
      </div>

      {/* Scrollable body */}
      <div className="flex flex-col gap-2.5 p-3 flex-1 overflow-y-auto custom-scrollbar">
        {/* Provider selector */}
        {keys.length > 0 && (
          <div className="flex gap-1 p-0.5 bg-muted/40 rounded border border-border/40">
            {keys.map((k) => {
              const meta = PROVIDER_META[k.provider];
              const isActive = selectedProvider === k.provider;
              return (
                <button
                  key={k.provider}
                  onClick={() => setSelectedProvider(k.provider)}
                  className={cn(
                    "flex-1 flex items-center justify-center gap-1 px-2 py-1 rounded text-[11px] font-medium transition-colors cursor-pointer",
                    isActive
                      ? "bg-card text-foreground shadow-xs border border-border"
                      : "text-muted-foreground hover:text-foreground hover:bg-muted/50",
                  )}
                >
                  <span
                    className="size-1.5 rounded-full shrink-0"
                    style={{ background: meta.color }}
                  />
                  <span>{meta.label.split(" ")[0]}</span>
                </button>
              );
            })}
          </div>
        )}

        {/* Prompt input */}
        <div className="relative rounded-md border border-border bg-card shadow-xs focus-within:border-primary focus-within:ring-1 focus-within:ring-primary/20 transition-colors">
          <textarea
            ref={textareaRef}
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter" && !e.shiftKey) {
                e.preventDefault();
                handleSend();
              }
            }}
            disabled={status === "loading"}
            placeholder={
              isC4
                ? "Describe your system… (e.g. Banking system with app and API)"
                : "Describe your architecture… (e.g. Chat app with WebSocket & Redis)"
            }
            rows={3}
            className="w-full resize-none bg-transparent px-3 pt-2.5 pb-1 text-xs placeholder:text-muted-foreground outline-none leading-relaxed font-sans disabled:opacity-50"
          />
          <div className="flex items-center justify-end gap-1.5 px-2 pb-2">
            <Button
              onClick={() => handleSend()}
              disabled={!canSend}
              size="xs"
              className="h-6 px-2 text-xs"
            >
              {status === "loading" ? (
                <IconLoader2 size={12} className="animate-spin" />
              ) : (
                <IconSend size={12} />
              )}
            </Button>
          </div>
        </div>

        {/* Status feedback */}
        {status === "loading" && (
          <div className="flex items-center gap-2 p-2.5 bg-muted/40 border border-border rounded text-xs">
            <IconLoader2
              size={14}
              className="animate-spin text-primary shrink-0"
            />
            <div>
              <div className="font-medium text-foreground">
                Generating diagram…
              </div>
              <div className="text-muted-foreground text-[10px]">
                Designing layout & connections
              </div>
            </div>
          </div>
        )}

        {status === "success" && (
          <div className="flex items-center gap-2 p-2.5 bg-emerald-500/10 border border-emerald-500/20 rounded text-xs">
            <IconCheck size={14} className="text-emerald-600 dark:text-emerald-400 shrink-0" />
            <div className="flex-1 min-w-0">
              <div className="font-medium text-emerald-600 dark:text-emerald-400 text-[11px]">
                Diagram generated!
              </div>
              <div className="text-muted-foreground text-[10px]">
                Rendered onto canvas. Use ⌘Z to undo.
              </div>
            </div>
            <Button
              onClick={() => {
                setStatus("idle");
                setPrompt(lastPrompt);
              }}
              variant="outline"
              size="xs"
            >
              <IconRefresh size={11} />
            </Button>
          </div>
        )}

        {status === "error" && (
          <div className="flex items-start gap-2 p-2.5 bg-destructive/10 border border-destructive/20 rounded text-xs">
            <IconAlertCircle
              size={14}
              className="text-destructive shrink-0 mt-0.5"
            />
            <div className="flex-1 min-w-0">
              <div className="font-medium text-destructive text-[11px]">
                Generation failed
              </div>
              <div className="text-muted-foreground text-[10px] truncate">
                {errorMsg}
              </div>
            </div>
            <Button
              onClick={handleRetry}
              variant="outline"
              size="xs"
            >
              <IconRefresh size={11} />
            </Button>
          </div>
        )}

        {/* Suggestions */}
        {status === "idle" && (
          <div className="space-y-1">
            <p className="text-[10px] font-mono font-medium text-muted-foreground uppercase px-0.5">
              Suggestions
            </p>
            <div className="space-y-1">
              {suggestions.map((s) => (
                <button
                  key={s.label}
                  onClick={() => {
                    setPrompt(s.prompt);
                    textareaRef.current?.focus();
                  }}
                  className="w-full flex items-center gap-2 px-2.5 py-1.5 rounded-md hover:bg-muted/60 text-left transition-colors group cursor-pointer border border-transparent hover:border-border/50"
                >
                  <div className="p-1 bg-muted rounded shrink-0 group-hover:text-primary transition-colors">
                    <s.icon
                      size={13}
                      className="text-muted-foreground"
                      stroke={1.5}
                    />
                  </div>
                  <div className="min-w-0 flex-1">
                    <div className="text-xs font-medium text-foreground leading-tight truncate">
                      {s.label}
                    </div>
                    <div className="text-[10px] text-muted-foreground leading-tight truncate">
                      {s.prompt}
                    </div>
                  </div>
                  <IconChevronRight
                    size={12}
                    className="text-muted-foreground/40 ml-auto shrink-0"
                  />
                </button>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Footer */}
      <div className="px-3 py-2 border-t border-border/50 bg-muted/10 shrink-0">
        <p className="text-[9px] font-mono text-muted-foreground leading-relaxed">
          Keys stored locally in browser storage.
        </p>
      </div>
    </div>
  );
}
